package com.ekertree.easypunch.pojo;

import lombok.ToString;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user
 */
@ToString
public class User {
    /**
     * Database Column Remarks:
     *   手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   qq号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   打卡地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.session_url
     *
     * @mbg.generated
     */
    private String sessionUrl;

    /**
     * Database Column Remarks:
     *   工作日打卡地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   假期打卡地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.home_address
     *
     * @mbg.generated
     */
    private String homeAddress;

    /**
     * Database Column Remarks:
     *   手机标识
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.user_agent
     *
     * @mbg.generated
     */
    private String userAgent;

    /**
     * Database Column Remarks:
     *   是否需要发送邮件
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.if_send_Email
     *
     * @mbg.generated
     */
    private Integer ifSendEmail;

    /**
     * Database Column Remarks:
     *   是否需要发送微信
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.if_send_wecheat
     *
     * @mbg.generated
     */
    private Integer ifSendWecheat;

    /**
     * Database Column Remarks:
     *   是否需要自动打卡
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.if_punch
     *
     * @mbg.generated
     */
    private Integer ifPunch;

    /**
     * Database Column Remarks:
     *   晨检打卡是否成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.morning
     *
     * @mbg.generated
     */
    private Integer morning;

    /**
     * Database Column Remarks:
     *   午检打卡是否成功
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.noon
     *
     * @mbg.generated
     */
    private Integer noon;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.phone
     *
     * @return the value of user.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.phone
     *
     * @param phone the value for user.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.qq
     *
     * @return the value of user.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.qq
     *
     * @param qq the value for user.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.session_url
     *
     * @return the value of user.session_url
     *
     * @mbg.generated
     */
    public String getSessionUrl() {
        return sessionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.session_url
     *
     * @param sessionUrl the value for user.session_url
     *
     * @mbg.generated
     */
    public void setSessionUrl(String sessionUrl) {
        this.sessionUrl = sessionUrl == null ? null : sessionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.address
     *
     * @return the value of user.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.address
     *
     * @param address the value for user.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.home_address
     *
     * @return the value of user.home_address
     *
     * @mbg.generated
     */
    public String getHomeAddress() {
        return homeAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.home_address
     *
     * @param homeAddress the value for user.home_address
     *
     * @mbg.generated
     */
    public void setHomeAddress(String homeAddress) {
        this.homeAddress = homeAddress == null ? null : homeAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.user_agent
     *
     * @return the value of user.user_agent
     *
     * @mbg.generated
     */
    public String getUserAgent() {
        return userAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.user_agent
     *
     * @param userAgent the value for user.user_agent
     *
     * @mbg.generated
     */
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent == null ? null : userAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.if_send_Email
     *
     * @return the value of user.if_send_Email
     *
     * @mbg.generated
     */
    public Integer getIfSendEmail() {
        return ifSendEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.if_send_Email
     *
     * @param ifSendEmail the value for user.if_send_Email
     *
     * @mbg.generated
     */
    public void setIfSendEmail(Integer ifSendEmail) {
        this.ifSendEmail = ifSendEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.if_send_wecheat
     *
     * @return the value of user.if_send_wecheat
     *
     * @mbg.generated
     */
    public Integer getIfSendWecheat() {
        return ifSendWecheat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.if_send_wecheat
     *
     * @param ifSendWecheat the value for user.if_send_wecheat
     *
     * @mbg.generated
     */
    public void setIfSendWecheat(Integer ifSendWecheat) {
        this.ifSendWecheat = ifSendWecheat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.if_punch
     *
     * @return the value of user.if_punch
     *
     * @mbg.generated
     */
    public Integer getIfPunch() {
        return ifPunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.if_punch
     *
     * @param ifPunch the value for user.if_punch
     *
     * @mbg.generated
     */
    public void setIfPunch(Integer ifPunch) {
        this.ifPunch = ifPunch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.morning
     *
     * @return the value of user.morning
     *
     * @mbg.generated
     */
    public Integer getMorning() {
        return morning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.morning
     *
     * @param morning the value for user.morning
     *
     * @mbg.generated
     */
    public void setMorning(Integer morning) {
        this.morning = morning;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.noon
     *
     * @return the value of user.noon
     *
     * @mbg.generated
     */
    public Integer getNoon() {
        return noon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.noon
     *
     * @param noon the value for user.noon
     *
     * @mbg.generated
     */
    public void setNoon(Integer noon) {
        this.noon = noon;
    }
}